reserva/urls.py
from django.urls import path

from reserva.views import criar_reserva

app_name = 'reserva'

urlpatterns = [
    path('criar/', criar_reserva, name='criar_reserva'),
]

rest_api/urls.py
from django.urls import path

from rest_framework.routers import SimpleRouter

from rest_api.views import AgendamentoModelViewSet, PetshopModelViewSet, hello_world

app_name = 'rest_api'

router = SimpleRouter(trailing_slash=False)
router.register('agendamento', AgendamentoModelViewSet)
router.register('petshop', PetshopModelViewSet)

urlpatterns = [
    path('hello_world', hello_world, name='hello_world_api'),
]

urlpatterns += router.urls

ultima/urls.py
from django.contrib import admin
from django.urls import path, include

from base.views import inicio, contato

urlpatterns = [
    path('', inicio),
    path('contato/', contato),
    path('reserva/', include('reserva.urls', namespace='reserva')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('rest_api.urls', namespace='api')),
]

base/models.py
from django.db import models

class Contato(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length=50)
    email = models.EmailField(verbose_name='E-mail', max_length=75)
    mensagem = models.TextField(verbose_name='Mensagem')
    data = models.DateTimeField(verbose_name='Data Envio', auto_now_add=True)
    lido = models.BooleanField(verbose_name='Lido', default=False, blank=True)

    def __str__(self):
        return f'{self.nome} [{self.email}]'
    class Meta:
        verbose_name = 'Formulário de Contato'
        verbose_name_plural = 'Formulários de Contatos'
        ordering = ['-data']

reserva/models.py
from django.db import models


class Petshop(models.Model):
    nome = models.CharField(verbose_name='Petshop', max_length=50)
    rua = models.CharField(verbose_name='Endereço', max_length=100)
    numero = models.CharField(verbose_name='Número', max_length=10)
    bairro = models.CharField(verbose_name='Bairro', max_length=50)

    def __str__(self):
        return self.nome

    def qtd_reserva(self):
        return self.reservas.count()


class Reserva(models.Model):
    TAMANHO_OPCOES = (
        (0, 'Pequeno'),
        (1, 'Médio'),
        (2, 'Grande'),
    )
    TURNO_OPCOES = (
        ('manhã', 'Manhã'),
        ('tarde', 'Tarde'),
    )
    nome = models.CharField(verbose_name='Nome', max_length=50)
    email = models.EmailField(verbose_name='E-mail')
    nome_pet = models.CharField(verbose_name='Nome do Pet', max_length=50)
    data = models.DateField(verbose_name='Data', help_text='dd/mm/aaaa')
    turno = models.CharField(verbose_name='Turno', max_length=10, choices=TURNO_OPCOES)
    tamanho = models.IntegerField(verbose_name='Tamanho', choices=TAMANHO_OPCOES)
    observacoes = models.TextField(blank=True)
    petshop = models.ForeignKey(
        Petshop, related_name='reservas', on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.nome}: {self.data} - {self.turno}'

    class Meta:
        verbose_name = 'Reserva de Banho'
        verbose_name_plural = 'Reservas de Banho'

rest_api/models.py
from django.db import models

# Create your models here.

base/forms.py
from django import forms
from base.models import Contato

class ContatoForm(forms.ModelForm):
    class Meta:
        model = Contato
        fields = ['nome', 'email', 'mensagem']

reserva/forms.py
from datetime import date
from django import forms
from reserva.models import Reserva

class ReservaForm(forms.ModelForm):

    def clean_data(self):
        data = self.cleaned_data['data']
        hoje = date.today()
        if data < hoje:
            raise forms.ValidationError('Não é possível realizar uma reserva para o passado!')
        return data

    class Meta:
        model = Reserva
        fields = [
            'nome', 'email', 'nome_pet', 'data', 'turno',
            'tamanho', 'petshop', 'observacoes',
        ]

base/views.py
from django.shortcuts import render
from base.forms import ContatoForm
from base.models import Contato

def inicio(request):
    return render(request, 'inicio.html')

def contato(request):
    sucesso = False
    form = ContatoForm(request.POST or None)
    if form.is_valid():
        sucesso = True
        form.save()
    contexto = {
        'telefone': '(99) 99999.9999',
        'responsavel': 'Maria da Silva Pereira',
        'form': form,
        'sucesso': sucesso
    }
    return render(request, 'contato.html', contexto)

reserva/views.py
from django.shortcuts import render
from reserva.forms import ReservaForm


def criar_reserva(request):
    form = ReservaForm(request.POST or None)
    sucesso = False
    if form.is_valid():
        form.save()
        sucesso = True
    contexto = {
        'form': form,
        'sucesso': sucesso,
    }
    return render(request, 'criar_reserva.html', contexto)

rest_api/views.py
from django.shortcuts import render

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from reserva.models import Petshop, Reserva
from rest_api.serializers import AgendamentoModelSerializer, PetshopModelSerializer

# Create your views here.

class AgendamentoModelViewSet(ModelViewSet):
    queryset = Reserva.objects.all()
    serializer_class = AgendamentoModelSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticatedOrReadOnly]


class PetshopModelViewSet(ReadOnlyModelViewSet):
    queryset = Petshop.objects.all()
    serializer_class = PetshopModelSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticatedOrReadOnly]


@api_view(['GET', 'POST'])
def hello_world(request):
    if request.method == 'POST':
        return Response({'message': f'Hello, {request.data.get("name")}'})

    return Response({'hello': 'World API'})

base/templates/contato.html
{% extends "inicio.html" %}
{% load bootstrap5 %}
{% block principal %}
<h1>Fale Conosco</h1>
<p>
    Envie uma mensagem através do formulário abaixo ou ligue para o telefone {{ telefone }}
    falando com o responsável {{ responsavel|upper }}
</p>
{% if sucesso %}
<p class="alert alert-success">Mensagem enviada com sucesso!</p>
{% else %}
<form action="" method="post" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    <hr>
    <button type="submit" class="btn btn-primary">Enviar Mensagem</button>
</form>
{% endif %}
{% endblock %}

base/templates/inicio.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pet Online - Reserve já o banho do seu Pet</title>
    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="/static/starter-template.css" rel="stylesheet">
  </head>
  <body>
    <div class="col-lg-8 mx-auto p-3 py-md-5">
    <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
            <span class="fs-4">Pet online</span>
        </a>
    </header>
    <main>
        {% block principal %}
        <h1>Reserve já o banho do seu Pet</h1>
        <a href="{% url 'reserva:criar_reserva' %}" class="btn btn-primary">Fazer Reserva</a>
        {% endblock %}
    </main>
    <footer class="pt-5 my-5 text-muted border-top">
        Curso Python Ultima School
    </footer>
    </div>
    <script src="/static/bootstrap.bundle.min.js"></script>
  </body>
</html>

reserva/templates/criar_reserva.html
{% extends "inicio.html" %}
{% load bootstrap5 %}
{% block principal %}
<h1>Faça a sua reserva</h1>
{% if sucesso %}
<p class="alert alert-success">Reserva realizada com sucesso, em breve iremos entrar em contato!</p>
{% else %}
<form action="" method="post" novalidate>
    {% csrf_token %}
    {% bootstrap_form form %}
    <hr>
    <button type="submit" class="btn btn-primary">Realizar Reserva</button>
</form>
{% endif %}
{% endblock %}